In [25]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json

numeric_df = pd.read_csv("../data/processed/numeric_values.csv")

In [5]:
numeric_df.describe()

           bedrooms     bathrooms         price          sqft
count  41098.000000  41182.000000  4.119900e+04  3.802100e+04
mean       3.235802      2.787699  1.587457e+06  8.152078e+04
std        1.485227      1.653202  3.941546e+06  2.406746e+06
min        0.000000      0.000000  7.950000e+02  0.000000e+00
25%        2.000000      2.000000  5.198000e+05  4.750000e+03
50%        3.000000      2.000000  7.750000e+05  7.405000e+03
75%        4.000000      3.000000  1.390000e+06  1.786000e+04
max       71.000000     67.000000  1.700000e+08  4.187423e+08

In [20]:
# drop extreme bedroom and bathroom numbers
def remove_outliers(df, col, lower=0.01, upper=0.99):
    low = df[col].quantile(lower)
    high = df[col].quantile(upper)
    
    return df[(df[col] >= low) & (df[col] <= high)]

df_clean = numeric_df.copy()
for col in ['bedrooms', 'bathrooms','price', 'sqft']:
    df_clean = remove_outliers(df_clean, col)

In [ ]:
df_clean.describe()
# still exists abnormal sqft value, manually set a range

           bedrooms     bathrooms         price           sqft
count  35943.000000  35943.000000  3.594300e+04   35943.000000
mean       3.231895      2.704365  1.224310e+06   30066.163011
std        1.149309      1.215184  1.324447e+06   76035.511480
min        1.000000      1.000000  1.729000e+05       0.000000
25%        2.000000      2.000000  5.249990e+05    4650.000000
50%        3.000000      2.000000  7.750000e+05    7368.000000
75%        4.000000      3.000000  1.350000e+06   15567.500000
max        7.000000      8.000000  1.099500e+07  781466.000000

In [22]:
df_clean = df_clean[
    (df_clean['sqft'] > 200) & 
    (df_clean['sqft'] < 20000)
]

In [23]:
df_clean.describe()

           bedrooms     bathrooms         price          sqft
count  25507.000000  25507.000000  2.550700e+04  25507.000000
mean       3.340730      2.702317  1.177180e+06   7201.069983
std        1.064893      1.131388  1.186432e+06   4028.140853
min        1.000000      1.000000  1.729000e+05    204.760000
25%        3.000000      2.000000  5.340000e+05   4791.000000
50%        3.000000      3.000000  7.950000e+05   6647.000000
75%        4.000000      3.000000  1.344750e+06   8865.000000
max        7.000000      8.000000  1.099500e+07  19995.000000

In [26]:
cols = ['bedrooms', 'bathrooms', 'price', 'sqft']

stats = {}

for col in cols:
    stats[f"{col}_min"] = float(df_clean[col].min())
    stats[f"{col}_max"] = float(df_clean[col].max())

# 存成 json 文件
with open('../data/processed/stats.json', 'w') as f:
    json.dump(stats, f, indent=2)